# Generated by Django 5.0.4 on 2026-03-02 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revenu', 'Objectif Revenu'), ('depense', 'Budget Dépenses')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('mois', models.IntegerField(blank=True, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('livreur', 'Livreur')], default='livreur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom client')),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cout_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('livrée', 'Livrée'), ('payée', 'Payée')], default='en attente', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_demarrage', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livreur', models.ForeignKey(blank=True, limit_choices_to={'role': 'livreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='api.entreprise')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='api.entreprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès entreprise',
                'verbose_name_plural': 'Accès entreprises',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revenu', 'Revenu'), ('depense', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.commande')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.entreprise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='api_command_statut_8922d7_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date'], name='api_command_date_0ee705_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['livreur'], name='api_command_livreur_3b1df5_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['entreprise'], name='api_command_entrepr_5df278_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepriseaccess',
            index=models.Index(fields=['user'], name='api_entrepr_user_id_ea70b9_idx'),
        ),
        migrations.AddIndex(
            model_name='entrepriseaccess',
            index=models.Index(fields=['entreprise'], name='api_entrepr_entrepr_acf7a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrepriseaccess',
            constraint=models.UniqueConstraint(fields=('user', 'entreprise'), name='uniq_user_entreprise_access'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='api_transac_type_7e7682_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='api_transac_date_26e12b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['entreprise'], name='api_transac_entrepr_75e289_idx'),
        ),
    ]
