# Generated by Django 6.0.5 on 2026-05-11 08:55

import django.db.models.deletion
from django.db import migrations, models


def assign_legacy_transactions(apps, schema_editor):
    Entreprise = apps.get_model('api', 'Entreprise')
    Transaction = apps.get_model('api', 'Transaction')

    transactions_without_entreprise = Transaction.objects.filter(entreprise__isnull=True)
    if not transactions_without_entreprise.exists():
        return

    fallback_entreprise, _ = Entreprise.objects.get_or_create(
        nom='Historique non attribue',
        defaults={
            'adresse': 'Transactions historiques sans entreprise',
        },
    )
    transactions_without_entreprise.update(entreprise=fallback_entreprise)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commande',
            name='api_command_statut_8922d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='api_command_date_0ee705_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='api_command_livreur_3b1df5_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='api_command_entrepr_5df278_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_longitude',
        ),
        migrations.AddField(
            model_name='transaction',
            name='categorie',
            field=models.CharField(choices=[('vente', 'Vente'), ('prestation', 'Prestation'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('fournitures', 'Fournitures'), ('transport', 'Transport'), ('utilitaires', 'Utilitaires'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(assign_legacy_transactions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur')], default='admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['categorie'], name='api_transac_categor_c40113_idx'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
