# Generated by Django 6.0.5 on 2026-05-12 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_commande_api_command_statut_8922d7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
