# Generated by Django 6.0.5 on 2026-05-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_entreprise_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.entreprise'),
        ),
    ]
