# Generated by Django 6.0.5 on 2026-05-12 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='notification_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objectif',
            name='seuil_alerte',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.CreateModel(
            name='BudgetNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=30)),
                ('periode_cle', models.CharField(max_length=80)),
                ('email_to', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.objectif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification budget',
                'verbose_name_plural': 'Notifications budget',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'objectif', 'niveau', 'periode_cle'), name='uniq_budget_notification_period')],
            },
        ),
    ]
