# Generated by Django 6.0.5 on 2026-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_objectif_notification_email_objectif_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectif',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='periode',
            field=models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('personnalise', 'Personnalisé')], default='mensuel', max_length=20),
        ),
    ]
